# Generated by Django 4.0 on 2022-01-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Slug', models.CharField(max_length=100)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
