# Generated by Django 4.0 on 2022-01-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Short_Description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
