# Generated by Django 4.0 on 2022-01-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogcomment',
        ),
    ]
