# Generated by Django 4.0 on 2022-02-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0006_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='userblog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000)),
                ('Description', models.TextField()),
                ('Short_Description', models.CharField(default='', max_length=200)),
                ('Slug', models.CharField(max_length=200)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
